settings:
  username: "WangzJi"
  commit_msg: "âš¡ Update README with recent activity"
  max_lines: 10
  readme_file: "README.md"
  disabled_events:
    - "comments"
  date_format: "MMM dd, yyyy"
  
messages:
  opened_issue: "ğŸ”¥ Opened issue #{number} in {repo}"
  opened_pr: "ğŸ’ª Opened PR #{number} in {repo}"
  merged_pr: "ğŸ‰ Merged PR #{number} in {repo}"
  created_repo: "ğŸ“¦ Created new repository {repo}"
  new_release: "ğŸš€ Released {release} in {repo}" 